import { Analytics } from "@vercel/analytics/react"
import Navigation from "./components/navigation";
import "./globals.css";

import { Goldman } from "next/font/google";

const goldman = Goldman({
  weight: ["400", "700"],
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={goldman.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
